steps:
  # Authenticate with GCP (built-in service account)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Authenticating with GCP"
        gcloud config set project $PROJECT_ID
        gcloud config set compute/region $REGION

  # Build and Push Docker Image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/nginx:latest",
        "."
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/nginx:latest"
      ]

  # Deploy to GKE cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Deploying to GKE cluster"
        gcloud container clusters get-credentials my-gke-cluster --region $REGION
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml

  # Verify deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Verifying deployment"
        kubectl get pods -n test-namespace
        kubectl describe service nginx-service -n test-namespace

options:
  env:
    - 'PROJECT_ID=bold-gadget-444515-n6'
    - 'REGION=us-central1'
