apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-namespace
spec:
  type: LoadBalancer
  selector:
    # app: nginx
    app: nginx-blue       # start with blue (Update the Service selector to app: nginx-green when you want to switch)
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
